// Business logic for explicit Addiction streak reset.
// Pure domain logic: no persistence, no UI, no side effects.
import type { Addiction, ResetReason, SyncInfo } from '../models/Addiction';
import type {
  ResetHistoryEntry,
  ResetHistoryId,
  ResetHistoryMetadata,
} from '../models/ResetHistory';
import { StreakService } from './StreakService';

export interface ResetStreakParams {
  /**
   * The addiction aggregate to reset.
   * This object will NOT be mutated.
   */
  addiction: Addiction;

  /**
   * Current time at which this operation is performed.
   * Passed explicitly for determinism and testability.
   */
  now: Date;

  /**
   * Unique identifier for the reset history entry.
   * Must be generated by the caller (pure function, no random/Date.now()).
   */
  resetId: ResetHistoryId;

  /**
   * Business reason for the reset.
   * Defaults to 'manual' when omitted.
   */
  reason?: ResetReason;

  /**
   * Optional free-form note describing the context.
   */
  note?: string;

  /**
   * When the reset actually happened in the user's life.
   * If omitted, defaults to `now`.
   */
  occurredAt?: Date;

  /**
   * Timezone offset (in minutes) at the moment of the reset.
   * Optional, but useful for analytics.
   */
  timezoneOffsetMinutes?: number;

  /**
   * Who initiated this reset.
   * Defaults to 'user'.
   */
  createdBy?: 'user' | 'system';
}

export interface ResetStreakResult {
  /**
   * Updated addiction aggregate with refreshed reset-related fields.
   */
  updatedAddiction: Addiction;

  /**
   * Newly created reset history entry describing this reset.
   */
  resetHistoryEntry: ResetHistoryEntry;
}

/**
 * Internal helper to validate Date instances.
 * Keeps errors explicit and easier to track in tests.
 */
function assertValidDate(value: Date, fieldName: string): void {
  if (!(value instanceof Date) || Number.isNaN(value.getTime())) {
    throw new Error(`resetAddictionStreak: Invalid Date provided for "${fieldName}".`);
  }
}

/**
 * Pure domain function that performs an explicit streak reset for an Addiction.
 *
 * Responsibilities:
 * - Updates the Addiction's reset-related fields (lastResetAt, longestStreakDays, resetCount, sync).
 * - Creates a ResetHistoryEntry capturing the reset as a domain event.
 * - Does NOT mutate the input Addiction.
 * - Does NOT perform any persistence, UI, or side effects.
 *
 * Edge cases:
 * - Archived addictions cannot be reset (throws).
 * - Resets with occurredAt in the future are rejected (throws).
 * - Multiple resets in the same 24-hour window are allowed and recorded,
 *   but will typically have previousStreakDays === 0.
 */
export function resetAddictionStreak(params: ResetStreakParams): ResetStreakResult {
  const { addiction, now, resetId, reason, note, occurredAt, timezoneOffsetMinutes, createdBy } =
    params;

  if (!addiction) {
    throw new Error('resetAddictionStreak: "addiction" is required.');
  }

  if (!resetId) {
    throw new Error('resetAddictionStreak: "resetId" is required.');
  }

  assertValidDate(now, 'now');
  assertValidDate(addiction.createdAt, 'addiction.createdAt');
  assertValidDate(addiction.lastResetAt, 'addiction.lastResetAt');

  const nowTime: number = now.getTime();
  const createdAtTime: number = addiction.createdAt.getTime();

  // Domain rule: we do not allow resetting an archived addiction.
  if (addiction.isArchived) {
    throw new Error('resetAddictionStreak: Cannot reset an archived addiction.');
  }

  // Domain rule: we cannot reset before the addiction exists.
  if (nowTime < createdAtTime) {
    throw new Error('resetAddictionStreak: "now" cannot be before addiction.createdAt.');
  }

  const effectiveOccurredAt: Date = occurredAt ?? now;
  assertValidDate(effectiveOccurredAt, 'occurredAt');
  const occurredAtTime: number = effectiveOccurredAt.getTime();

  // Resets in the future relative to "now" are considered invalid.
  if (occurredAtTime > nowTime) {
    throw new Error(
      'resetAddictionStreak: "occurredAt" cannot be in the future relative to "now".'
    );
  }

  const effectiveReason: ResetReason = reason ?? 'manual';
  const effectiveCreatedBy: 'user' | 'system' = createdBy ?? 'user';

  // Calculate the streak length immediately before the reset,
  // using the moment when the reset actually happened (occurredAt).
  const previousStreakDays: number = StreakService.calculateCurrentStreakDaysFromAddiction(
    addiction,
    effectiveOccurredAt
  );

  // The streak after a classic reset is explicitly 0 days.
  const newStreakDays: number = 0;

  // Update the longest streak only if this reset ends a new personal best.
  let nextLongestStreakDays: number = addiction.longestStreakDays;
  if (previousStreakDays > addiction.longestStreakDays) {
    nextLongestStreakDays = previousStreakDays;
  }

  const nextResetCount: number = addiction.resetCount + 1;

  let nextSync: SyncInfo | undefined = addiction.sync;
  if (addiction.sync) {
    nextSync = {
      ...addiction.sync,
      revision: addiction.sync.revision + 1,
      updatedAt: now,
      // lastSyncedAt is intentionally preserved (no sync happens here).
    };
  }

  const updatedAddiction: Addiction = {
    ...addiction,
    lastResetAt: effectiveOccurredAt,
    longestStreakDays: nextLongestStreakDays,
    resetCount: nextResetCount,
    sync: nextSync,
  };

  const metadata: ResetHistoryMetadata | undefined =
    effectiveCreatedBy || timezoneOffsetMinutes !== undefined || occurredAt !== undefined
      ? {
          createdBy: effectiveCreatedBy,
          // Consider it backfilled if the occurredAt is strictly before the time of recording.
          isBackfilled: occurredAt ? occurredAtTime < nowTime : false,
          timezoneOffsetMinutes,
        }
      : undefined;

  const resetHistoryEntry: ResetHistoryEntry = {
    id: resetId,
    addictionId: addiction.id,
    occurredAt: effectiveOccurredAt,
    recordedAt: now,
    reason: effectiveReason,
    previousStreakDays,
    newStreakDays,
    note,
    metadata,
    // sync is intentionally left undefined; it can be managed at the data/sync layer later.
    sync: undefined,
  };

  return {
    updatedAddiction,
    resetHistoryEntry,
  };
}
