// Repository interface for Addiction entity
import type { Addiction, AddictionId } from '@/domain/models/Addiction';

/**
 * Input type for creating a new Addiction.
 * All fields except `id` are required (id is generated by repository).
 */
export interface CreateAddictionInput {
  name: string;
  createdAt: Date;
  lastResetAt: Date;
  longestStreakDays?: number;
  resetCount?: number;
  isArchived?: boolean;
  archivedAt?: Date;
}

/**
 * Input type for updating an existing Addiction.
 * All fields are optional (partial update).
 */
export interface UpdateAddictionInput {
  name?: string;
  lastResetAt?: Date;
  longestStreakDays?: number;
  resetCount?: number;
  isArchived?: boolean;
  archivedAt?: Date;
}

/**
 * Repository interface for Addiction persistence operations.
 *
 * This abstraction allows swapping implementations (SQLite, in-memory, future sync layer).
 */
export interface IAddictionRepository {
  /**
   * Creates a new Addiction entity.
   * @param input - Addiction data (id will be generated)
   * @returns Created Addiction with generated id
   * @throws DatabaseError if creation fails
   */
  create(input: CreateAddictionInput): Promise<Addiction>;

  /**
   * Retrieves an Addiction by its id.
   * @param id - Unique identifier
   * @returns Addiction entity or null if not found
   * @throws DatabaseError if query fails
   */
  findById(id: AddictionId): Promise<Addiction | null>;

  /**
   * Retrieves all Addiction entities.
   * @returns Array of all Addiction entities (empty array if none exist)
   * @throws DatabaseError if query fails
   */
  findAll(): Promise<Addiction[]>;

  /**
   * Updates an existing Addiction entity.
   * @param id - Unique identifier of the Addiction to update
   * @param input - Partial update data
   * @returns Updated Addiction entity
   * @throws DatabaseError if update fails or entity not found
   */
  update(id: AddictionId, input: UpdateAddictionInput): Promise<Addiction>;

  /**
   * Deletes an Addiction entity by id.
   * @param id - Unique identifier
   * @throws DatabaseError if deletion fails or entity not found
   */
  delete(id: AddictionId): Promise<void>;
}
