// Repository interface for ResetHistoryEntry entity
import type { AddictionId } from '@/domain/models/Addiction';
import type { ResetHistoryEntry, ResetHistoryId } from '@/domain/models/ResetHistory';

/**
 * Input type for creating a new ResetHistoryEntry.
 * All fields except `id` are required (id is generated by repository).
 */
export interface CreateResetHistoryInput {
  addictionId: AddictionId;
  occurredAt: Date;
  recordedAt: Date;
  reason: 'relapse' | 'slip' | 'planned' | 'manual' | 'unknown';
  previousStreakDays: number;
  newStreakDays: number;
  note?: string;
}

/**
 * Repository interface for ResetHistoryEntry persistence operations.
 *
 * This abstraction allows swapping implementations (SQLite, in-memory, future sync layer).
 */
export interface IResetHistoryRepository {
  /**
   * Creates a new ResetHistoryEntry.
   * @param input - Reset history data (id will be generated)
   * @returns Created ResetHistoryEntry with generated id
   * @throws DatabaseError if creation fails
   */
  create(input: CreateResetHistoryInput): Promise<ResetHistoryEntry>;

  /**
   * Retrieves a ResetHistoryEntry by its id.
   * @param id - Unique identifier
   * @returns ResetHistoryEntry or null if not found
   * @throws DatabaseError if query fails
   */
  findById(id: ResetHistoryId): Promise<ResetHistoryEntry | null>;

  /**
   * Retrieves all ResetHistoryEntry entities for a specific addiction.
   * @param addictionId - The addiction to get reset history for
   * @returns Array of ResetHistoryEntry entities, ordered by occurredAt descending (most recent first)
   * @throws DatabaseError if query fails
   */
  findByAddictionId(addictionId: AddictionId): Promise<ResetHistoryEntry[]>;

  /**
   * Retrieves all ResetHistoryEntry entities across all addictions.
   * Useful for analytics, sync, and future features.
   * @returns Array of all ResetHistoryEntry entities, ordered by occurredAt descending
   * @throws DatabaseError if query fails
   */
  findAll(): Promise<ResetHistoryEntry[]>;
}
